import { VideoV2Manifest } from "./types";

// Auto-generated by remotion/scripts/sync-video-v2-data.ts
// Do not edit manually.
export const VIDEO_V2_DATA: VideoV2Manifest = {
  "generatedAt": "2026-02-18T16:45:02.846Z",
  "proof": {
    "chain": "opBNB Testnet",
    "chainId": 5611,
    "contractAddress": "0x8F4aF898fc2f28281D2a51d322b586C1DA0481f9",
    "txHash": "0x7c4b2c3d5bb8dd1aaa34c9dd7a218b0ab91f607d9faac237b40d6500378eab77",
    "contractExplorer": "https://opbnb-testnet-scan.bnbchain.org/address/0x8F4aF898fc2f28281D2a51d322b586C1DA0481f9",
    "txExplorer": "https://opbnb-testnet-scan.bnbchain.org/tx/0x7c4b2c3d5bb8dd1aaa34c9dd7a218b0ab91f607d9faac237b40d6500378eab77"
  },
  "cases": [
    {
      "id": "clean_baseline",
      "title": "Clean Baseline",
      "problem": "Judges need a low-risk baseline to verify the pipeline can produce a reproducible green verdict.",
      "repoUrl": "https://github.com/octocat/Hello-World",
      "commitSha": "7fd1a60b01f91b314f59955a4e4d4e80d8edf11d",
      "expectedLevel": "green",
      "expectedDimensions": [],
      "score": 0,
      "level": "green",
      "fingerprint": "0xe89688d203c73e040cca08740fc43c998fdbeba4d144b2c627a8a96dc6d38796",
      "reportHash": "0x77d21dace9aab44e6d2320a95a60e3e980d00cb2f9fa015d6ec4bbdcbf26b2a2",
      "dimensions": [],
      "attestOutcome": "allowed",
      "attestMessage": "Onchain attestation confirmed",
      "txHash": "0x8edd560fb3ba17aa8f3f289e23f625ebaa5ccce5c94bf329b881d46190e9d216",
      "evidence": {
        "homeImage": "v2/cases/clean_baseline/home.png",
        "auditImage": "v2/cases/clean_baseline/audit.png",
        "fingerprintImage": "v2/cases/clean_baseline/fingerprint.png",
        "flowJson": "v2/cases/clean_baseline/flow.json",
        "reportJson": "v2/cases/clean_baseline/report.json",
        "attestJson": "v2/cases/clean_baseline/attest.json"
      }
    },
    {
      "id": "remote_execution_risk",
      "title": "Remote Execution Risk",
      "problem": "A common supply-chain pattern pipes remote scripts directly into shell execution.",
      "repoUrl": "https://github.com/Homebrew/install",
      "commitSha": "5838cadbb2c7beb17c7dcdddb5f0dba6c4780feb",
      "expectedLevel": "red",
      "expectedDimensions": [
        "remote_execution"
      ],
      "score": 99,
      "level": "red",
      "fingerprint": "0x1b2de516d9e09f0bed70f2d1951236c45eb7f762a47348a2ed66cc06ea1e3a94",
      "reportHash": "0x78047171c8de5d1dc591e4001a6de1ea429535b6b7fd38d6a5497789a2461dba",
      "dimensions": [
        "remote_execution",
        "credential_access",
        "suspicious_network",
        "permission_mismatch"
      ],
      "attestOutcome": "denied",
      "attestMessage": "Only green reports are eligible for attestation",
      "evidence": {
        "homeImage": "v2/cases/remote_execution_risk/home.png",
        "auditImage": "v2/cases/remote_execution_risk/audit.png",
        "fingerprintImage": "v2/cases/remote_execution_risk/fingerprint.png",
        "flowJson": "v2/cases/remote_execution_risk/flow.json",
        "reportJson": "v2/cases/remote_execution_risk/report.json",
        "attestJson": "v2/cases/remote_execution_risk/attest.json"
      }
    },
    {
      "id": "credential_access_risk",
      "title": "Credential Access Risk",
      "problem": "Repository code frequently reads runtime secrets through environment variables and should be flagged for review.",
      "repoUrl": "https://github.com/OWASP/NodeGoat",
      "commitSha": "c5cb68a7084e4ae7dcc60e6a98768720a81841e8",
      "expectedLevel": "yellow",
      "expectedDimensions": [
        "credential_access"
      ],
      "score": 63,
      "level": "yellow",
      "fingerprint": "0x5c2f0f87c5e96e11e9f4a0e121cf34116ceaebc5216442f274fe98412d074956",
      "reportHash": "0x17f9256ce24259dc3ce2c75078fe0a1e07392f2486ae30f559484aa8c68defcf",
      "dimensions": [
        "credential_access",
        "obfuscation"
      ],
      "attestOutcome": "denied",
      "attestMessage": "Only green reports are eligible for attestation",
      "evidence": {
        "homeImage": "v2/cases/credential_access_risk/home.png",
        "auditImage": "v2/cases/credential_access_risk/audit.png",
        "fingerprintImage": "v2/cases/credential_access_risk/fingerprint.png",
        "flowJson": "v2/cases/credential_access_risk/flow.json",
        "reportJson": "v2/cases/credential_access_risk/report.json",
        "attestJson": "v2/cases/credential_access_risk/attest.json"
      }
    }
  ],
  "event": {
    "txHash": "0x7c4b2c3d5bb8dd1aaa34c9dd7a218b0ab91f607d9faac237b40d6500378eab77",
    "contractAddress": "0x8f4af898fc2f28281d2a51d322b586c1da0481f9",
    "blockNumber": 128753935,
    "fingerprint": "0xe89688d203c73e040cca08740fc43c998fdbeba4d144b2c627a8a96dc6d38796",
    "score": 0,
    "attester": "0xf709b2fF3Fa85c7919f5120239eaDdbcddC3c3A3",
    "reportHash": "0xcb4124b028b16da50ea7d5e6d4563bde749236dc605d0a1e84225be374c15d2d",
    "repo": "https://github.com/octocat/Hello-World",
    "commit": "7fd1a60b01f91b314f59955a4e4d4e80d8edf11d",
    "timestamp": 1770997810
  },
  "aiEvidence": {
    "loops": 6,
    "screenshots": [
      "v2/ai-log/screenshots/shot-01.png",
      "v2/ai-log/screenshots/shot-02.png",
      "v2/ai-log/screenshots/shot-03.png",
      "v2/ai-log/screenshots/shot-04.png",
      "v2/ai-log/screenshots/shot-05.png",
      "v2/ai-log/screenshots/shot-06.png"
    ],
    "keyframes": [
      "v2/keyframes/scene-01-problem.png",
      "v2/keyframes/scene-02-scan.png",
      "v2/keyframes/scene-03-onchain-proof.png",
      "v2/keyframes/scene-04-hero.png"
    ],
    "evidenceIndexPath": "docs/ai-log/EVIDENCE_INDEX.md"
  },
  "urls": {
    "repoUrl": "https://github.com/zzw4257/ClawShield",
    "demoUrl": "https://clawshield.vercel.app",
    "videoUrl": "media/video/clawshield-demo-v2.mp4",
    "apiHealthUrl": "http://localhost:8787/api/health"
  },
  "media": {
    "voiceoverPath": "v2/audio/clawshield-voiceover-v2.mp3",
    "subtitlePath": "subtitles/clawshield-v2.srt"
  }
};
