/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ClawShieldRegistry {
  export type AttestationStruct = {
    fingerprint: BytesLike;
    score: BigNumberish;
    reportURI: string;
    reportHash: BytesLike;
    repo: string;
    commit: string;
    attester: AddressLike;
    timestamp: BigNumberish;
    revoked: boolean;
    reasonURI: string;
  };

  export type AttestationStructOutput = [
    fingerprint: string,
    score: bigint,
    reportURI: string,
    reportHash: string,
    repo: string,
    commit: string,
    attester: string,
    timestamp: bigint,
    revoked: boolean,
    reasonURI: string
  ] & {
    fingerprint: string;
    score: bigint;
    reportURI: string;
    reportHash: string;
    repo: string;
    commit: string;
    attester: string;
    timestamp: bigint;
    revoked: boolean;
    reasonURI: string;
  };
}

export interface ClawShieldRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "getHistory"
      | "getLatest"
      | "isAttester"
      | "maxAttestableScore"
      | "owner"
      | "renounceOwnership"
      | "revoke"
      | "setAttester"
      | "setMaxAttestableScore"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Attested"
      | "MaxAttestableScoreUpdated"
      | "OwnershipTransferred"
      | "Revoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [BytesLike, BigNumberish, string, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAttestableScore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttester",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAttestableScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLatest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAttester", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxAttestableScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAttestableScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AttestedEvent {
  export type InputTuple = [
    fingerprint: BytesLike,
    score: BigNumberish,
    attester: AddressLike,
    reportURI: string,
    reportHash: BytesLike,
    repo: string,
    commit: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fingerprint: string,
    score: bigint,
    attester: string,
    reportURI: string,
    reportHash: string,
    repo: string,
    commit: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fingerprint: string;
    score: bigint;
    attester: string;
    reportURI: string;
    reportHash: string;
    repo: string;
    commit: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAttestableScoreUpdatedEvent {
  export type InputTuple = [newMaxAttestableScore: BigNumberish];
  export type OutputTuple = [newMaxAttestableScore: bigint];
  export interface OutputObject {
    newMaxAttestableScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedEvent {
  export type InputTuple = [
    fingerprint: BytesLike,
    attester: AddressLike,
    reasonURI: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fingerprint: string,
    attester: string,
    reasonURI: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fingerprint: string;
    attester: string;
    reasonURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClawShieldRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClawShieldRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClawShieldRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [
      fingerprint: BytesLike,
      score: BigNumberish,
      reportURI: string,
      reportHash: BytesLike,
      repo: string,
      commit: string
    ],
    [void],
    "nonpayable"
  >;

  getHistory: TypedContractMethod<
    [fingerprint: BytesLike],
    [ClawShieldRegistry.AttestationStructOutput[]],
    "view"
  >;

  getLatest: TypedContractMethod<
    [fingerprint: BytesLike],
    [ClawShieldRegistry.AttestationStructOutput],
    "view"
  >;

  isAttester: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  maxAttestableScore: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revoke: TypedContractMethod<
    [fingerprint: BytesLike, reasonURI: string],
    [void],
    "nonpayable"
  >;

  setAttester: TypedContractMethod<
    [attester: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setMaxAttestableScore: TypedContractMethod<
    [newMaxAttestableScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      fingerprint: BytesLike,
      score: BigNumberish,
      reportURI: string,
      reportHash: BytesLike,
      repo: string,
      commit: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [fingerprint: BytesLike],
    [ClawShieldRegistry.AttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatest"
  ): TypedContractMethod<
    [fingerprint: BytesLike],
    [ClawShieldRegistry.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAttester"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxAttestableScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [fingerprint: BytesLike, reasonURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttester"
  ): TypedContractMethod<
    [attester: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxAttestableScore"
  ): TypedContractMethod<
    [newMaxAttestableScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Attested"
  ): TypedContractEvent<
    AttestedEvent.InputTuple,
    AttestedEvent.OutputTuple,
    AttestedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAttestableScoreUpdated"
  ): TypedContractEvent<
    MaxAttestableScoreUpdatedEvent.InputTuple,
    MaxAttestableScoreUpdatedEvent.OutputTuple,
    MaxAttestableScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Revoked"
  ): TypedContractEvent<
    RevokedEvent.InputTuple,
    RevokedEvent.OutputTuple,
    RevokedEvent.OutputObject
  >;

  filters: {
    "Attested(bytes32,uint8,address,string,bytes32,string,string,uint256)": TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
    Attested: TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;

    "MaxAttestableScoreUpdated(uint8)": TypedContractEvent<
      MaxAttestableScoreUpdatedEvent.InputTuple,
      MaxAttestableScoreUpdatedEvent.OutputTuple,
      MaxAttestableScoreUpdatedEvent.OutputObject
    >;
    MaxAttestableScoreUpdated: TypedContractEvent<
      MaxAttestableScoreUpdatedEvent.InputTuple,
      MaxAttestableScoreUpdatedEvent.OutputTuple,
      MaxAttestableScoreUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Revoked(bytes32,address,string,uint256)": TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;
    Revoked: TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;
  };
}
